# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZWViMmMyNTVjNTI4ODMzM2Y0NjQyODkxZDcyMjIzOWIwZjU5YmU3NjgzNjIyY2IzMjZiYzc5YjVmMGM5NjU1ZGZjODhiYTAzMmU5NGZlZGU0OTIyMmMxNTFhN2QzZGY2ZjFiNGJlZmIxNDMzNWZhYzM0YmZkYzFjZTk2MzRlM2M=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
